# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: clock_in_records_db
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
